### ISSUE TITLE
Edges vs intervals

### ISSUE THREAD

**Issue by hyanwong** [hyanwong/GeneticInheritanceGraph#13]
We have got into some problems in tskit because we use the word "edge" to mean an interval with a parent & child, whereas in our formal definition (in the ARG paper) we define an edge to be made up of a set of (possibly more than one) intervals, each of which have the same parent and child.

I propose that in a GIG, we don't call it an "edges" table, but instead call it an "intervals" table, and there is an extra (optional) column which contains an "edge" ID. The edge then specifies a path of transmission from a parent to a child. We could state that this column can be null (-1), in which case intervals with the same parent & child can be treated as belonging to the same (unspecified) edge.

It's purely a terminological change, but experience with `tskit` suggests to me that this might be useful?

**Comment by duncanMR** [comment]
That makes sense to me; besides the terminology change, I have been thinking an edge ID column would be useful because it allows us to group together all the genomic changes that correspond to a particular structural variant in the genome. I think we could feasibly generalise the mathematical definition of the genomic ARG to the GIG if we define edges in that way, although we have much to still figure out there.

**Comment by hyanwong** [comment]
We could define an edge ID in the Intervals table here:

https://github.com/hyanwong/GeneticInheritanceGraph/blob/79f32a072583dbb0ee5b894f3b1a2dba91a6e446/GeneticInheritanceGraph/tables.py#L24

Let's see if we need it

**Comment by hyanwong** [comment]
Closing, as we have decided to call this the intervals table for the moment. We can always add an edge ID if needed.
